### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by keith8496**

### CODE REVIEW

**Comment by keith8496** [comment]
This PR was an accident. I mean to update my fork.

**Comment by peternewman** [comment]
No worries @keith8496 , it's cool that you found it, and so quickly, and that you presumably have found it useful already?

**Comment by keith8496** [comment]
I've been experimenting with this and with [sofie-atem-connection ](https://github.com/nrkno/sofie-atem-connection) via [atem-connection-nodered](https://github.com/haydendonald/atem-connection-nodered). I'm going to use the latter because they're a natural fit into my Node-Red architecture. If I was starting over from scratch and wasn't using dashboard extensions in Node-Red, I would use your proxy with MQTT.

There are a lot of people on forums and Facebook asking for the functionality your proxy provides. I'll try to advertise for you.

**Comment by keith8496** [comment]
@peternewman - I recommend you create a Docker container for the proxy. That's how I was testing it. That might help with adoption. I can send you my Docker compose/build file if that helps. It might be a little hacky and need some tweaking to be fit for public consumption.

**Comment by peternewman** [comment]
Sorry, I should have been clearer last time @keith8496 , the code is currently nothing to do with me, I can't take any credit whatsoever, it's all @MartijnBraam work, it's just they don't currently provide a clone on GitHub.

Please continue to point people to the original repo here:
https://git.sr.ht/~martijnbraam/pyatem

But they could use this unofficial mirror if they find it useful.

FWIW I've actually just been doing a little bit of work on the Blackmagic converter code to try and add more units I've got access to, I just went for this workflow as I like GitHub's interface in terms of diff (via PR) and I felt having two separate repos (mine and the unofficial mirror) made that easier/clearer.

**Pull request closed without merging**
